### ISSUE TITLE
The music stops 

### ISSUE THREAD

**Issue by dragonxtek** [tomasmcm/SpotiWeb#12] opened 2016-09-22 15:55 UTC
When I'm listenig music, sometimes the music stops. It solves pressing play again. 
I don't know if the connection it's bad, traffic shaping or if it's a bug, but It would be a good idea to implement a persistent connection.

**Comment by tomasmcm** [comment] 2016-09-23 18:22
@dragonxtek again, if you could please try playing music through your normal browser at play.spotify.com just to check if the problem is on my side or not.

**Comment by dragonxtek** [comment] 2016-09-26 21:30
I had the same problem on the web (the music stops), for this reason I want to use a client. With the official spotify app I don't have this problem.

**Comment by tomasmcm** [comment] 2016-09-27 09:05
This app is a wrapper of the web version, so if it happens in the web app it will happen in this desktop app as well.

**Comment by tomasmcm** [comment] 2016-10-09 17:13
I'm closing this due to the fact that the bug is outside of SpotiWeb's scope.

**Closed as completed by tomasmcm** 2016-10-09 17:13 UTC
